name: cmake CI of jrl-cmakemodules

on: [push,pull_request]

jobs:
  build-ubuntu:

    runs-on: [ubuntu-18.04] 

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: |
        cd _unittests
        cmake -P test_pkg-config.cmake
